Model: ''
BaseIOSchema: 2012.0
BaseIOLevel: Detail
IOYear: 2012.0
PrimaryRegionAcronym: US
ModelRegionAcronyms:
- US
- GA
ModelType: US
BasePriceType: PRO
BasewithDefinitions: no
ReferenceCurrencyYear: 0.0
CommoditybyIndustryType: Commodity
ScrapIncluded: yes
SatelliteTable: []
Demand: []
Indicators: []
